import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
// import styles from '@/styles/Home.module.css'
import Layout from '@/components/Layout'
import profilePic from '../../public/images/profile/developer-pic-1.png'
import AnimatedText from '@/components/AnimatedText'
import Link from 'next/link'
import { LinkArrow } from '@/components/Icons'
import ChatBot from '@/components/ChatBot'
import LightBulb from'../../public/images/svgs/miscellaneous_icons_1.svg'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=' flex items-center text-dark w-full min-h-screen dark:text-light'> 
      <Layout className='pt-0'>

        <div className='flex items-center justify-between w-full'> 
          <div className='w-1/2'> 
            <Image src={profilePic} alt='Raj Profile Pic' className='w-full h-auto'></Image>
          </div>
          <div className='w-1/2 flex flex-col items-center self-center'>
            <AnimatedText  text='Transforming complex challenges into elegant solutions' className='!text-4xl !text-left'></AnimatedText>
            <p className='my-4 text-base font-medium'>
              My personal website is my playground where I can constantly learn and improve my skills. Exploring new techniques and tools with each new project, This approach has not only helped me grow as a professional but has also opened up new opportunities for me. I am excited to share my experiences and learnings with you through my blog.
            </p>
            <div className='flex item-center self-start mt-2'>
              <Link href='/ra_resume.docx' target='_blank' 
              className='flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light
               hover:text-dark hover border-2 border-solid border-transparent hover:border-dark dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light hover:dark:border-light ' download={true}>
              Resume <LinkArrow className={'w-6 ml-1 '}></LinkArrow></Link>
              <Link href='mailto:raj.a@msn.com' target='_blank'
              className='ml-4 text-lg font-medium capitalize text-dark underline dark:text-light'
              >Contact</Link>
            </div>
          </div>
        </div>

      </Layout>
      <ChatBot></ChatBot>
      <div className='absolute right-8 bottom-8 inline-block w-24'>
        <Image src={LightBulb} alt='Raj Ambalpady' className='w-full h-auto'></Image>
      </div>
      </main>
    </>
  )
}
